repos:
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.10
        args: [ --config=pyproject.toml ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3.10
        args: [ --config=.flake8 ]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        language_version: python3.9
        args: [ --config=pyproject.toml ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3.10
        files: "\\.(py)$"
        args: [ --settings-path=pyproject.toml ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        language_version: python3.10
        args: [ "--config=pyproject.toml", "-rq"]
        additional_dependencies: ["toml"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: check-case-conflict
      - id: no-commit-to-branch
        language_version: python3.10
        args: [ "--branch", "main" ]
